# Generated by Django 3.0.3 on 2020-02-18 01:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('personal_website_url', models.CharField(max_length=100)),
                ('shortened_personal_website_url', models.CharField(max_length=100)),
                ('friendships', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), null=True, size=None)),
            ],
        ),
    ]
