# Generated by Django 3.0.3 on 2020-02-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name001', models.CharField(max_length=40)),
                ('name002', models.CharField(max_length=40)),
            ],
        ),
    ]
