# Generated by Django 3.0.3 on 2020-02-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_search', '0002_friendships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendships',
            name='name001',
        ),
        migrations.RemoveField(
            model_name='friendships',
            name='name002',
        ),
        migrations.AddField(
            model_name='friendships',
            name='expert_id_001',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendships',
            name='expert_id_002',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
