# Generated by Django 3.0.3 on 2020-02-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert_search', '0003_auto_20200218_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='friendships',
        ),
    ]
